#apiVersion: v1
#kind: Service
#metadata:
#  name: wireflow-turn-svc
#  namespace: wireflow
#spec:
#  ports:
#    - protocol: UDP
#      port: 3478
#      targetPort: 3478
#      nodePort: 3478
#  selector:
#    k8s-app: wireflow-turn
#  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: wireflow-control-svc
#  namespace: wireflow
#spec:
#  ports:
#    - protocol: TCP
#      name: http
#      port: 8080
#      targetPort: 8080
#      nodePort: 32138
#    - protocol: TCP
#      name: grpc
#      port: 6060
#      targetPort: 6060
#      nodePort: 6060
#  selector:
#    k8s-app: wireflow-control
#  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: wireflow-signaling-svc
#  namespace: wireflow
#spec:
#  ports:
#    - protocol: TCP
#      port: 6066
#      targetPort: 6066
#      nodePort: 6066
#  selector:
#    k8s-app: wireflow-signaling
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: wireflow-web
  labels:
    app: wireflow-web
spec:
  selector:
    app: wireflow-web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP