apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkany-control
  namespace: linkany
  labels:
    k8s-app: linkany-control
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: linkany-control
  template:
    metadata:
      labels:
        k8s-app: linkany-control
    spec:
      imagePullSecrets:
        - name: ali-registry
      containers:
        - name: linkany-control
          image: registry.cn-hangzhou.aliyuncs.com/linkany-io/linkany
          imagePullPolicy: Always
          command: [ "linkany", "manager" ]
          volumeMounts:
            - mountPath: /app/control.yaml
              name: conf
              subPath: control.yaml
      volumes:
        - name: conf
          configMap:
            name: linkany-control-config
            items:
              - key: control.yaml
                path: control.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: linkany-control-svc
  namespace: linkany
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 32138
    - protocol: TCP
      name: grpc
      port: 32051
      targetPort: 32051
      nodePort: 32051
  selector:
    k8s-app: linkany-control
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkany-control-config
  namespace: linkany
data:
  control.yaml: |
    listen: :8080
    database:
      host: 81.68.109.143
      port: 3306
      name: linkany
      user: root
      password: dhvuYUoxnSZMavdJ