## Append samples of your project ##
resources:
- wireflowcontroller_v1alpha1_node.yaml
- wireflowcontroller_v1alpha1_wireflownetwork.yaml
- label1-policy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
