apiVersion: wireflowcontroller.wireflow.run/v1alpha1
kind: WireflowPolicy
metadata:
  labels:
    app.kubernetes.io/name: wireflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-sample
spec:
  peerSelector:
    matchLabels:
      app: test
  network: wireflow-default-net
  ingressRule:
    - from:
        - peerSelector:
            matchLabels:
              app: test

